// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0XpvPOrgOL-D_TE6hCaOU2F1iihYsXl4',
    appId: '1:461285608934:web:4719850eb9d3c0dfc31a27',
    messagingSenderId: '461285608934',
    projectId: 'portfolio-c9269',
    authDomain: 'portfolio-c9269.firebaseapp.com',
    storageBucket: 'portfolio-c9269.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAddF8Zp-j2fo__MfVcQuaGxtO5y_ZZLKA',
    appId: '1:461285608934:android:93b339dabab72e9bc31a27',
    messagingSenderId: '461285608934',
    projectId: 'portfolio-c9269',
    storageBucket: 'portfolio-c9269.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc3englOanjqV2zHl7mcQdoAP7Qxrxaik',
    appId: '1:461285608934:ios:239883047253e801c31a27',
    messagingSenderId: '461285608934',
    projectId: 'portfolio-c9269',
    storageBucket: 'portfolio-c9269.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc3englOanjqV2zHl7mcQdoAP7Qxrxaik',
    appId: '1:461285608934:ios:239883047253e801c31a27',
    messagingSenderId: '461285608934',
    projectId: 'portfolio-c9269',
    storageBucket: 'portfolio-c9269.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0XpvPOrgOL-D_TE6hCaOU2F1iihYsXl4',
    appId: '1:461285608934:web:6f3f6561d7fb9430c31a27',
    messagingSenderId: '461285608934',
    projectId: 'portfolio-c9269',
    authDomain: 'portfolio-c9269.firebaseapp.com',
    storageBucket: 'portfolio-c9269.firebasestorage.app',
  );
}
