// // import 'package:flutter/material.dart';
// // import 'package:flutter_riverpod/flutter_riverpod.dart';
// // import 'package:firebase_core/firebase_core.dart';
// // import 'app/routes/app_routes.dart';
// // import 'firebase_options.dart'; // generated by FlutterFire CLI
// //
// // void main() async {
// //   WidgetsFlutterBinding.ensureInitialized();
// //
// //   // Initialize Firebase before running the app
// //   await Firebase.initializeApp(
// //     options: DefaultFirebaseOptions.currentPlatform,
// //   );
// //
// //   // Global error screen override
// //   ErrorWidget.builder = (FlutterErrorDetails details) {
// //     return Material(
// //       color: Colors.red.shade50,
// //       child: Padding(
// //         padding: const EdgeInsets.all(20.0),
// //         child: Center(
// //           child: Text(
// //             "⚠️ UI Error: ${details.exceptionAsString()}",
// //             style: const TextStyle(color: Colors.red, fontSize: 16),
// //             textAlign: TextAlign.center,
// //           ),
// //         ),
// //       ),
// //     );
// //   };
// //
// //   runApp(
// //     const ProviderScope(
// //       child: MyApp(),
// //     ),
// //   );
// // }
// //
// // class MyApp extends StatelessWidget {
// //   const MyApp({super.key});
// //
// //   @override
// //   Widget build(BuildContext context) {
// //     return MaterialApp(
// //       title: "Portfolio",
// //       debugShowCheckedModeBanner: false,
// //       initialRoute: AppRoutes.splash,
// //       routes: AppRoutes.routes,
// //
// //       onUnknownRoute: (settings) {
// //         return MaterialPageRoute(
// //           builder: (_) => Scaffold(
// //             body: Center(
// //               child: Text(
// //                 "❌ Unknown Route: ${settings.name}",
// //                 style: const TextStyle(fontSize: 18),
// //               ),
// //             ),
// //           ),
// //         );
// //       },
// //
// //       navigatorObservers: [RouteObserver<ModalRoute<void>>()],
// //     );
// //   }
// // }
//
//
// // lib/main.dart
//
// import 'dart:io';
//
// import 'package:flutter/material.dart';
// import 'package:flutter_riverpod/flutter_riverpod.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'package:flutter/foundation.dart';
// import 'package:portfolio/modules/about/about_me.dart';
// import 'package:portfolio/modules/home/home_screen.dart';
// import 'package:portfolio/modules/projects/projects_screen.dart';
//
// import 'app/constants/custom_app_bar.dart';
// import 'firebase_options.dart';
//
// void main() async {
//   WidgetsFlutterBinding.ensureInitialized();
//   // await dotenv.load(fileName: ".env");
//   await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
//   );
//
//   // 👇 Temporary line for iOS-style testing on Android / Chrome
//   debugDefaultTargetPlatformOverride = TargetPlatform.iOS;
//
//   if (kIsWeb) {
//     print('Running on Web');
//   } else {
//     print('Running on non-Web (Android/iOS)');
//   }
//
//   runApp(const ProviderScope(child: MyApp()));
// }
//
// /*
// void main() async {
//   WidgetsFlutterBinding.ensureInitialized();
//
//   // 👇 pass DefaultFirebaseOptions.currentPlatform always!
//   await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
//   );
//   // await NotificationHandler.initNotifications(); // ✅ add this line
//
//   runApp(const ProviderScope(child: MyApp()));
// }
// */
//
// class MyApp extends ConsumerWidget {
//   const MyApp({super.key});
//   // await NotificationHandler.initNotifications(); // ✅ add this line
//
//   @override
//   Widget build(BuildContext context,WidgetRef ref) {
//     FlutterError.onError = (FlutterErrorDetails details) {
//       if (details.exceptionAsString().contains('setState() called after dispose()')) {
//         // Ignore this specific error
//         debugPrint('⚠️ Ignored: setState() called after dispose()');
//       } else {
//         FlutterError.presentError(details);
//       }
//     };
//
//
//     // final themeMode = ref.watch(userSettingsControllerProvider);
//     return MaterialApp(
//
//       debugShowCheckedModeBanner: false,
//
//       title: 'Martify',
//       // theme: sys,
//       // theme: AppTheme.lightTheme,
//       // darkTheme: AppTheme.darkThem
//       // e,
//
//       home: PortfolioRoot()
//     );
//   }
// }
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:portfolio/app/routes/app_routes.dart';
import 'app/constants/custom_app_bar.dart';
import 'app/theme/app_theme.dart';
import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends ConsumerWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final isDarkMode = ref.watch(isDarkThemeProvider);
    final colors = getCurrentColors(isDarkMode);

    return MaterialApp(
      title: 'Portfolio',
      debugShowCheckedModeBanner: false,

      navigatorKey: AppRoutes.navigatorKey,
      onGenerateRoute: AppRoutes.onGenerateRoute,
      onUnknownRoute: (settings) => MaterialPageRoute(
        builder: (_) => Scaffold(
          body: Center(child: Text("❌ Unknown Route: ${settings.name}")),
        ),
      ),

      // 👇 Always use PortfolioLayout for home
      home: const PortfolioLayout(initialPage: "home"),

      theme: ThemeData(
        brightness: Brightness.light,
        primaryColor: colors['primaryColor'],
        scaffoldBackgroundColor: colors['background'],
      ),
      darkTheme: ThemeData(
        brightness: Brightness.dark,
        primaryColor: colors['primaryColor'],
        scaffoldBackgroundColor: colors['background'],
      ),
      themeMode: isDarkMode ? ThemeMode.dark : ThemeMode.light,
    );
  }
}
